505: fail with message when webhook not enabled and minReplicas is nil
streamnative/function-mesh pull request #543
Opened 2022-12-05 11:02 UTC by imaffe

We have two methods to avoid the nil pointer exception.

Method 1 is to provide a default value for the possible nil fields just like in the admission webhook. However adding default value in the code could potentially make it harder to find where the config value comes from when debugging. And it also require us to change two places if we were to change the default value logic.

Method 2 is simple: fail early but with hint messages on what caused the issue and how to resolve the issue. It guides the user to use a newer version of function-mesh with webhooks enabled.

2022-12-06 01:08 UTC, jiangpengcheng commented on controllers/spec/hpa.go
> +	panicIfNil(maxReplicas, "MaxReplicas should not be nil but is nil; This is likely because the webhook is not installed properly so it does not have a default value")
I think the `maxReplicas` is optional?

2022-12-07 02:09 UTC, Huanli-Meng commented
@imaffe do we need to update the docs for this PR? Thanks

2022-12-12 09:42 UTC, tpiperatgod commented
I think we can put the logic to determine if `spec.minReplicas` is nil at the beginning of the reconciliation

2023-02-06 23:08 UTC, nlu90 requested changes

2023-02-06 23:08 UTC, nlu90 commented on controllers/common.go
> +	}
we should never panic in a controller's reconciliation loop

2023-02-24 02:46 UTC, freeznet commented
close by https://github.com/streamnative/function-mesh/pull/582

2023-02-24 02:46 UTC, closed without merging